schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)
{
  query: Query
}

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

type GameNews
  @join__type(graph: NEWS)
{
  newsId: String!
  appId: Int!
  title: String!
  url: String!
}

type GameReview
  @join__type(graph: REVIEW)
{
  recommendationId: Int!
  appId: Int!
  review: String!
  language: String!
  votesUp: Int!
}

type GameSummary
  @join__type(graph: NEWS, key: "appId")
  @join__type(graph: REVIEW, key: "appId")
  @join__type(graph: SUMMARY, key: "appId")
{
  appId: Int!
  news: [GameNews] @join__field(graph: NEWS)
  reviews: [GameReview] @join__field(graph: REVIEW)
  name: String! @join__field(graph: SUMMARY)
  developer: String @join__field(graph: SUMMARY)
  publisher: String @join__field(graph: SUMMARY)
  positive: Int @join__field(graph: SUMMARY)
  negative: Int @join__field(graph: SUMMARY)
  owners: Int @join__field(graph: SUMMARY)
  dateAdded: String! @join__field(graph: SUMMARY)
}

type GameSummaryConnection
  @join__type(graph: SUMMARY)
{
  count: Int!
  cursor: String
  items: [GameSummary!]!
}

scalar join__FieldSet

enum join__Graph {
  NEWS @join__graph(name: "news", url: "https://7ub1g1q46l.execute-api.sa-east-1.amazonaws.com/subgraphs/game-news")
  REVIEW @join__graph(name: "review", url: "https://7ub1g1q46l.execute-api.sa-east-1.amazonaws.com/subgraphs/game-review")
  SUMMARY @join__graph(name: "summary", url: "https://7ub1g1q46l.execute-api.sa-east-1.amazonaws.com/subgraphs/game-summary")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type Query
  @join__type(graph: NEWS)
  @join__type(graph: REVIEW)
  @join__type(graph: SUMMARY)
{
  gameNews(appId: Int!): [GameNews!]! @join__field(graph: NEWS)
  gameReviews(appId: Int!, language: String): [GameReview!]! @join__field(graph: REVIEW)
  gameSummaries(cursor: String): GameSummaryConnection! @join__field(graph: SUMMARY)
  gameSummary(appId: Int!): GameSummary @join__field(graph: SUMMARY)
}