name: Deploy to AWS Lambda

run-name: "[${{ github.event_name }} - ${{ github.ref }}] Deploying lambda"

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository
  
on: [push,workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Build game-summary
        run: |
          cd game-summary

          echo 'Listing files'
          echo '----------------'
          ls
          echo ''

          echo 'Installing Packages'
          echo '----------------'
          npm ci
          echo ''

          echo 'Bulding project'
          echo '----------------'
          npm run build
          echo ''

          echo 'Listing dist'
          echo '----------------'
          ls ./dist

      - name: Build game-review
        run: |
          cd game-review

          echo 'Listing files'
          echo '----------------'
          ls
          echo ''

          echo 'Installing Packages'
          echo '----------------'
          npm ci
          echo ''

          echo 'Bulding project'
          echo '----------------'
          npm run build
          echo ''

          echo 'Listing dist'
          echo '----------------'
          ls ./dist

      - name: Build game-news
        run: |
          cd game-news

          echo 'Listing files'
          echo '----------------'
          ls
          echo ''

          echo 'Installing Packages'
          echo '----------------'
          npm ci
          echo ''

          echo 'Bulding project'
          echo '----------------'
          npm run build
          echo ''

          echo 'Listing dist'
          echo '----------------'
          ls ./dist

      - name: Build game-query
        run: |
          cd game-query

          echo 'Listing files'
          echo '----------------'
          ls
          echo ''

          echo 'Installing Packages'
          echo '----------------'
          npm ci
          echo ''

          echo 'Bulding project'
          echo '----------------'
          npm run build
          echo ''

          echo 'Listing dist'
          echo '----------------'
          ls ./dist

      - name: Build steam-fetch
        run: |
          cd steam-fetch

          echo 'Listing files'
          echo '----------------'
          ls
          echo ''

          echo 'Installing Packages'
          echo '----------------'
          npm ci
          echo ''

          echo 'Bulding project'
          echo '----------------'
          npm run build
          echo ''

          echo 'Listing dist'
          echo '----------------'
          ls ./dist

      - name: Deploy Lambda Function Summary
        uses: aws-actions/aws-lambda-deploy@v1.1.2
        with:
          function-name: game-summary
          code-artifacts-dir: ${{ github.workspace }}/game-summary/dist
          handler: index.handler
          runtime: nodejs24.x
          timeout: 10
          memory-size: 256
          role: ${{ secrets.AWS_LAMBDA_ROLE }}
          environment: '{"FAILED_QUERY_TOPIC_ARN":"${{ secrets.FAILED_QUERY_TOPIC_ARN }}","AWS_LAMBDA_EXEC_WRAPPER":"/opt/otel-instrument"}'
          layers: '["arn:aws:lambda:${{ vars.AWS_REGION }}:615299751070:layer:AWSOpenTelemetryDistroJs:15"]'
          tracing-config: '{"Mode":"Active"}'

      - name: Deploy Lambda Function Review
        uses: aws-actions/aws-lambda-deploy@v1.1.2
        with:
          function-name: game-review
          code-artifacts-dir: ${{ github.workspace }}/game-review/dist
          handler: index.handler
          runtime: nodejs24.x
          timeout: 10
          memory-size: 256
          role: ${{ secrets.AWS_LAMBDA_ROLE }}
          environment: '{"AWS_LAMBDA_EXEC_WRAPPER":"/opt/otel-instrument"}'
          layers: '["arn:aws:lambda:${{ vars.AWS_REGION }}:615299751070:layer:AWSOpenTelemetryDistroJs:15"]'
          tracing-config: '{"Mode":"Active"}'

      - name: Deploy Lambda Function News
        uses: aws-actions/aws-lambda-deploy@v1.1.2
        with:
          function-name: game-news
          code-artifacts-dir: ${{ github.workspace }}/game-news/dist
          handler: index.handler
          runtime: nodejs24.x
          timeout: 10
          memory-size: 256
          role: ${{ secrets.AWS_LAMBDA_ROLE }}
          environment: '{"AWS_LAMBDA_EXEC_WRAPPER":"/opt/otel-instrument"}'
          layers: '["arn:aws:lambda:${{ vars.AWS_REGION }}:615299751070:layer:AWSOpenTelemetryDistroJs:15"]'
          tracing-config: '{"Mode":"Active"}'

      - name: Deploy Lambda Function Query
        uses: aws-actions/aws-lambda-deploy@v1.1.2
        with:
          function-name: game-query
          code-artifacts-dir: ${{ github.workspace }}/game-query/dist
          handler: index.handler
          runtime: nodejs24.x
          timeout: 10
          memory-size: 256
          role: ${{ secrets.AWS_LAMBDA_ROLE }}
          environment: '{"AWS_LAMBDA_EXEC_WRAPPER":"/opt/otel-instrument"}'
          layers: '["arn:aws:lambda:${{ vars.AWS_REGION }}:615299751070:layer:AWSOpenTelemetryDistroJs:15"]'
          tracing-config: '{"Mode":"Active"}'

      - name: Deploy Lambda Function Steam Fetch
        uses: aws-actions/aws-lambda-deploy@v1.1.2
        with:
          function-name: steam-fetch
          code-artifacts-dir: ${{ github.workspace }}/steam-fetch/dist
          handler: fetch.handler
          runtime: nodejs24.x
          timeout: 120
          memory-size: 256
          role: ${{ secrets.AWS_LAMBDA_ROLE }}
          environment: '{"AWS_LAMBDA_EXEC_WRAPPER":"/opt/otel-instrument"}'
          layers: '["arn:aws:lambda:${{ vars.AWS_REGION }}:615299751070:layer:AWSOpenTelemetryDistroJs:15"]'
          tracing-config: '{"Mode":"Active"}'

      - run: echo "🍏 This job's status is ${{ job.status }}."
